import type { Metadata } from "next";
import "./globals.css";
import { Navbar } from "@/components/navbar";
import {IBM_Plex_Sans} from "next/font/google"


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const IBMPlexSans = IBM_Plex_Sans({
  weight: ['400', '500', '600', '700'],
  style: ['italic', 'normal'],
  display: 'swap',
  subsets: ['latin']
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={IBMPlexSans.className}>
      <body
        className="flex min-h-full flex-col bg-white"
      >
        <Navbar/>
        <main className="flex-grow container mx-auto px-4 py-8" >{children}</main>
      </body>
    </html>
  );
}
